# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for npm
  # Dependabot auto-detects when pnpm is used. Do not change this value to pnpm!
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Raise pull requests for version updates against `main` branch
    target-branch: "main"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      # Check for npm updates at 8am every Monday
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Asia/Tokyo"
    # Specify reviewers for pull requests
    reviewers:
      - "senhongo"
